exporter_port: $EXPORTER_PORT|9090 # the port that exposes cost metrics
polling_interval_seconds: $POLLING_INTERVAL_SECONDS|28800 # by default it is 8 hours
metric_name: azure_daily_cost # change the metric name if needed
metric_name_usd: azure_daily_cost_usd # change the metric name if needed

group_by:
  enabled: true
  groups:
    - type: Dimension
      name: ServiceName
      label_name: ServiceName
  merge_minor_cost:
    # if this is enabled, minor cost that is below the threshold will be merged into one group
    enabled: false
    threshold: 10
    tag_value: other

target_azure_accounts:
  # here defines a list of target Azure accounts
  # it should be guaranteed that all the Azure accounts have the same set of keys (in this example they are Publisher, ProjectName, and EnvironmentName)
  - TenantId: ad402983-7c5d-4e94-83ba-1fc05474d7d4
    Subscription: 8be789eb-7d62-433a-a4a5-37624f8db208
    ProjectName: SNF
    EnvironmentName: prod
    AdditionalGroupBy: ResourceGroup
    # AndMoney
  - TenantId: 15e848b8-e8aa-4790-88aa-827c7cc27bfa
    Subscription: 7e2ff23d-ffe3-4346-8470-47c77e44f2bd
    ProjectName: andmoney-shared
    EnvironmentName: prod
    AdditionalGroupBy: None
  - TenantId: 15e848b8-e8aa-4790-88aa-827c7cc27bfa
    Subscription: 7c51e024-19d5-4229-8728-4d030887d778
    ProjectName: bconomy
    EnvironmentName: prod
    AdditionalGroupBy: None
  - TenantId: 15e848b8-e8aa-4790-88aa-827c7cc27bfa
    Subscription: cd0a0d9d-78f4-46dc-a866-0098b946a2ec
    ProjectName: bookme
    EnvironmentName: prod
    AdditionalGroupBy: None
  - TenantId: 15e848b8-e8aa-4790-88aa-827c7cc27bfa
    Subscription: 806c22d7-5a7c-48cf-9841-0a770fb73d28
    ProjectName: youngmoney
    EnvironmentName: prod
    AdditionalGroupBy: None
